apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
