---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: portfolio
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAxu66dgusYKxDTKrAZxOlpWuhb0TLpaAFMnJvZf2DIZCkau7ZW2HWsiqbxZXbWRRl84oLRYRyPQXMnbvuD5T/CaUy9PYv7xoC0xXRs+ACTDK/rgaTVjGDaaNmjG4A97LbghYW5l8UbiFNasjNiijyRWaa43is0G8lAo3sAmEHqng/OmjSd7SOHsBplYIuq7Y/qVcxUgM4944w/BngXZtan/i0biAIyKljIaheXnWU5L6Ia+k/qI6/r0/moe7BkvHeeniKRUEXHApLmZ/y87v3raky5nVUgb7HvpPVX7DNl+fdWUn3NgaRiLWq/J5VQEDJvp4QP36xAvOFAqxZyx1cEzKCoippaPinDMCFRv3uO1d+RUaks6lLRBwgQ73xj9pId6BcbXZKmxELkYZgKQirmds0bmj8aNf6ax+bo5sZV0JnlKs+U7EBijL2ykLLxkMiNkyESpZm03Lry1nuagqqM1HbtBcFgcSoSNEvWWqkgU7oPR+baKH/CKxVF3VKc8PfMrVvsYjTqn5/G8iA43j59NnaKlhh7Ce9ECnLredLutnOmD/bYaHS+OBclrdTHQnI7YtV9wN+dZ4o+AfnSV59OlTc92MYM6Zhjzku83DWLN2RAeltKG8geupQ0oJ96e7lsDkkn1DKUilX0iZ958BktGbgtCaja4lFNYbxNKw9kCZvbzr3WKxRC5bPiVh1y58UVHh+h0nTtHnCdNw==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: portfolio
