apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "A DB password is required. Pass it with --set secrets.postgresPassword=..." .Values.secrets.postgresPassword | quote }}
